import './globals.css'
import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
} from 'next/font/google'
import { Hero } from '@/components/Hero'
import { Copyright } from '@/components/Copyright'
import { SignIn } from '@/components/SignIn'
import { ReactNode } from 'react'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} bg-blue-900 font-sans text-gray-600`}
      >
        <main className="grid min-h-screen grid-cols-1 lg:grid-cols-2">
          <div className="hidden lg:block">
            <div className="relative min-h-screen flex flex-col items-start justify-between overflow-hidden px-28 py-16">
              <div className="absolute right-0 top-1/2 h-[288px] w-[526px] -translate-y-1/2 translate-x-1/2 rounded-full bg-blue-400 opacity-50 blur-full"></div>
              <SignIn />

              <Hero />

              <Copyright />
            </div>
          </div>

          <div className="flex max-h-screen flex-col bg-white overflow-y-scroll">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
